version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: backend
  frontend:
    build:
      context: ./employee-ui
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    container_name: frontend
    depends_on:
      - backend
